CREATE TABLE IF NOT EXISTS conversation_sessions (
   conversation_id CHAR(36) NOT NULL PRIMARY KEY,
   last_response_id VARCHAR(255) NOT NULL,
   updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

